// This file is auto-generated by the Lumexia Initialization script.
// Do not edit this file manually.

export const procurementTypes = {
  "produced": "76357509-6076-45b4-9f5d-afad51770d91",
  "purchased": "37f8654a-d819-48fd-85ca-6ed7dd51922b"
} as const;
