// This file is auto-generated by the Lumexia Initialization script.
// Do not edit this file manually.

export const transactionTypes = {
  "bprConsumption": "85ff0278-7e42-41e1-94dd-cd54fd72e061",
  "adjustmentRemoval": "b4c00bef-6e1f-47e3-bd9c-1cfc184462ed",
  "orderFulfillmentRemoval": "e8a3d3db-0ebd-43c2-b784-610159f028e6",
  "adjustmentAddition": "f768afb0-2902-44dd-b2df-9f2d319c754c",
  "procurement": "74860086-7f62-4f5d-9b41-4a7ac054aa13"
} as const;
