// This file is auto-generated by the Lumexia Initialization script.
// Do not edit this file manually.

export const transactionTypes = {
  "bprConsumption": "924dc721-1a4d-43e9-86ee-3e1c5ffcae5a",
  "adjustmentRemoval": "49c2c8b3-728d-4fce-96c6-720fe6b4d307",
  "orderFulfillmentRemoval": "7f2bca34-8736-4235-9302-bf281d55820c",
  "adjustmentAddition": "1628606e-3380-4106-8be2-795ac7a3bed8",
  "procurement": "ba7f1842-35c9-497a-9018-b9fa8fab56e6"
} as const;
